name: context examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        run: |
          echo "step1 $my_action"
          echo "step2 $my_actor"
        env:
          MY_ACTION: ${{github.action}}
          my_actor: ${{github.actor}}